/* Formatted on 5/25/2016 3:55:16 PM (QP5 v5.163.1008.3004) */
SELECT INVOICE_GID,
       INVOICE_XID,
       INVOICE_TYPE,
       INVOICE_SOURCE,
       ENTERED_BY_GL_USER_GID,
       INVOICE_NUMBER,
       SERVPROV_ALIAS_QUAL_GID,
       SERVPROV_ALIAS_VALUE
  FROM INVOICE